### ISSUE TITLE
File placements not consistent

### ISSUE THREAD

**Issue by dkoslicki** [nlapier2/Metalign#10]
When running:
```
~/Desktop/MetalignV2/Metalign$ python3 metalign.py test/RL_S001__insert_270.fq data/ --output test/metalign_results.tsv --low_mem
```
The `*.kmc_pre` and `*.kmc_suf` end up in the `test` folder. But when using a fresh installation (to test alternate ways to install) and pointing to a different `data` folder elsewhere:
```
~/Desktop/MetalignV3/Metalign$ python3 metalign.py test/RL_S001__insert_270.fq ~/Desktop/MetalignV2/Metalign/data/ --output test/results.tsv --low_mem
```
then the kmc files end up in `MetalignV3/Metalign/data/<random folder name>`. Note how I was calling the data file that existed outside of the main Metalign folder. This causes Metalign to stall out since the `60mers_intersection_dump.fa` file also ends up in the wrong place.

**Comment by nlapier2** [comment]
I believe this is addressed by the new hanging fix.
