### ISSUE TITLE
Script hanging problem (and proposed solution)

### ISSUE THREAD

**Issue by dkoslicki** [nlapier2/Metalign#11]
@nlapier2 So I figured out the probably source of the program hanging: python3 vs python2 for CMash:
After setting up the data, this hangs:
```bash
python3 -m venv VE3
source VE3/bin/activate
.\setup_libraries.sh
# This hangs:
python3 metalign.py test/RL_S001__insert_270_1M_subset.fq data/ --output test/RL_S001__insert_270_1M_subset_results.tsv  

# this is the thing causing the hang:
python3 StreamingQueryDNADatabase.py ../../data/r7aqo9zw/60mers_intersection_dump.fa ../../data/cmash_db_n1000_k60.h5 ../../test/CMash_out.csv 30-60-10 -c 0 -r 10000 -v -f ../../data/cmash_filter_n1000_k60_30-60-10.bf --sensitive  
```
So instead, try python2, and it doesn't hang:
```bash
virtualenv VE2
source VE2/bin/activate
cd CMash
pip install -r requirements.txt 

# this runs just fine and does not hang:
python StreamingQueryDNADatabase.py ../../data/r7aqo9zw/60mers_intersection_dump.fa ../../data/cmash_db_n1000_k60.h5 ../../test/CMash_out.csv 30-60-10 -c 0 -r 10000 -v -f ../../data/cmash_filter_n1000_k60_30-60-10.bf --sensitive  

# this works too (oddly enough, since it's being called with python3, so it only looks like installing CMash with python2 is required):
python3 metalign.py test/RL_S001__insert_270_1M_subset.fq data/ --output test/RL_S001__insert_270_1M_subset_results.tsv  

# also works (as it appears metalign.py is python2/3 compliant):
python metalign.py test/RL_S001__insert_270_1M_subset.fq data/ --output test/RL_S001__insert_270_1M_subset_results.tsv   
```
So possible solutions (with my assessment of ease of implementation):
1. Make setup_libraries.sh use python2 when installing CMash (probably via a virtualenv) (easy)
2. See why marisa-trie isn't working with python3 (their repo says it's python3 compatible) (medium)
3. Refactor CMash so it's python3 compliant (hard)

**Comment by dkoslicki** [comment]
Update: looks like it's not marisa-trie that's causing the issue, since the code is stalling out [here](https://github.com/dkoslicki/CMash/blob/master/scripts/StreamingQueryDNADatabase.py#L266-L271). So it looks like it might be a python2 vs python3 thing with the `pool.map` function instead.

**Comment by nlapier2** [comment]
Great, thanks for the help in figuring this out! Locally, I've gotten the "easy" (virtualenv) solution working, and I am currently working on getting the repo/docker/docs updated. We could look into the more fundamental pool.map issue eventually. It would be ideal if the repo was compatible with both python2 and python3.

**Comment by nlapier2** [comment]
Repo/docs/docker updated. Closing this for now since we have something working, though we could revisit the more fundamental fixes eventually.

**Comment by dkoslicki** [comment]
Actually, I may have just solved the issue and made it python2 and python3 compliant, so I'll re-open momentarily, then comment after testing if it's fixed.

**Comment by dkoslicki** [comment]
Ok, looks like it works now. See [this issue in the CMash repo](https://github.com/dkoslicki/CMash/issues/12). I'll need to change the `setup_libraries.sh` script to reflect this.

**Comment by dkoslicki** [comment]
@nlapier2 Feel free to test on your end too in order to confirm it's working with just python3. Feel free to close if it does

**Comment by nlapier2** [comment]
Works for me! Do you think we should put the --user flag for pip installing requirements, since users (esp. on servers) may not have root permissions?

**Comment by dkoslicki** [comment]
Good point! Go ahead and add the `--user` flag
