### ISSUE TITLE
Can metalign be used for profiling (micro)eukaryotes?

### ISSUE THREAD

**Issue by Anto007** [nlapier2/Metalign#13]
Can metalign be used for profiling (micro)eukaryotes in metagenomes? I believe the answer is "No" but I would appreciate if you could confirm this.

**Comment by nlapier2** [comment]
Hi there, Metalign is capable of profiling single-celled eukaryotes. Of course, reference databases have fewer reference genomes for eukaryotes than for bacteria, so that has to be kept in mind.

**Comment by Anto007** [comment]
Many thanks for your kind clarification. I'm curious to know why you chose to leave out plants and animals (esp. Homo sapiens; of course, I'm aware that it is best if human reads are filtered out prior to analysis)? For example, in clinical metagenomic libraries, it will be useful to know the relative abundance of reads from human and similarly, the relative abundance of plant pollen in environmental metagenomes

**Comment by nlapier2** [comment]
That's an interesting point. We left them out because we only want to profile microorganisms, but I see how their inclusion could be relevant for some contexts. This is a feature we'll think about adding.
