### ISSUE TITLE
setup.py and PyPI, Bioconda deployment?

### ISSUE THREAD

**Issue by peterk87** [nlapier2/Metalign#19]
Are there plans to restructure Metalign as a Python application that can be deployed to PyPI and maybe Bioconda?

Thanks!

**Comment by dkoslicki** [comment]
@peterk87 I'm going to merge this issue with #20 if you don't mind, with the goal of:

- [ ] setup.py
- [ ] github release
- [ ] conda release
- [ ] PyPI release

It may happen that it gets to conda first given the external dependencies, but we shall see. Also, as a heads up, given the tight integration with [CMash](https://github.com/dkoslicki/CMash) and the [current work in CMash to get Python3+ compliant](https://github.com/dkoslicki/CMash/tree/python3) not yet pushed to PyPI, the PyPI release will take some time.
