### ISSUE TITLE
KMC bad_alloc error

### ISSUE THREAD

**Issue by dkoslicki** [nlapier2/Metalign#2]
It appears that the cause of this is due to the `-sm` and `-m200` flag in [these lines](https://github.com/nlapier2/Metalign/blob/master/select_db.py#L56-L58). Indeed, from the command line,
```bash
KMC/bin/./kmc -v -k60 -m200 -sm -fa -ci2 -cs3 -t48 -jlog_sample test/small_cami_low.fasta test/reads_60mers test/
```
throws the `bad_alloc` error, while
```bash
KMC/bin/./kmc -v -k60 -fa -ci2 -cs3 -t48 -jlog_sample test/small_cami_low.fasta test/reads_60mers test/
```
does not. I vote we let KMC determine the amount of memory to use, rather than to try and determine it ourselves. Alternatively, you can make this an option and have it default to, say, 75% of available system memory (though this may cause issues in server/batch environments).

**Comment by nlapier2** [comment]
Great find! I did the former (letting KMC determine it). Thanks!
