### ISSUE TITLE
Version number, setup.py, github, PyPI, Conda releases

### ISSUE THREAD

**Issue by peterk87** [nlapier2/Metalign#20]
Hello, 

Where can I find the version number of Metalign? It doesn't seem to be anywhere in the source. 

Thanks!

**Comment by dkoslicki** [comment]
@nlapier2 can you include:

- [x] A license (I suggest BSD, an example can be had [here](https://github.com/dib-lab/khmer/blob/master/LICENSE))
- [ ] a `setup.py` script that includes a version number (I suggest starting at 0.1.0 or 1.0.0 depending on your feeling about the stability of the API at the moment). You can find an example [here](https://github.com/dkoslicki/CMash/blob/python3/setup.py).

After this, we can make a release in github and also tag it with the version number in the `setup.py` script.

Let me know if you don't have time and I can also do it later in the week.

**Comment by nlapier2** [comment]
While you were writing that, I added the version number to the README. The version number I had was 0.9.1, in accordance with the docker versions I had been developing.

There's a LICENSE file with the MIT license.

I do think it would be better to add the setup.py and do GitHub releases in the future.

**Comment by dkoslicki** [comment]
@nlapier2 Don't know how I missed the license file earlier, whoops!

**Comment by dkoslicki** [comment]
TODO's:

- [x] setup.py
- [x] github release
- [x] conda release
- [ ] PyPI release

PyPI release currently blocking on [this issue in CMash](https://github.com/dkoslicki/CMash/issues/13).

It may happen that it gets to conda first given the external dependencies, but we shall see. Also, as a heads up, given the tight integration with CMash and [the current work in CMash to get Python3+ compliant](https://github.com/dkoslicki/CMash/issues/13) not yet pushed to PyPI, the PyPI release will take some time.

**Comment by peterk87** [comment]
@nlapier2 @dkoslicki Thanks for looking into these things!

To help with packaging the app, it may be useful to slightly restructure the project to fit typical Python package structure:

```
<project_root>
├── <root files like .gitignore, README.md, LICENSE, etc>
├── metalign
│   ├── __init__.py
│   ├── <other modules>
│   └── metalign.py
└── tests
    ├── __init__.py
    └── test_metalign_restruct.py
```

You could put some info into `metalign/__init__.py`:

```python
"""Top-level package for metalign."""

__author__ = """Your Name"""
__email__ = 'your.name@email.com'
__version__ = '0.9.1'
```
So that you can import the version and other info to display in other parts of the app.

**Comment by dkoslicki** [comment]
@nlapier2 I think I've figured out the issue. Let me do a bit more local testing and I'll let you know

**Comment by dkoslicki** [comment]
Officially merged and up on Bioconda! https://github.com/bioconda/bioconda-recipes/pull/21711
