### ISSUE TITLE
Refactor how CMash is called

### ISSUE THREAD

**Issue by dkoslicki** [nlapier2/Metalign#27]
Currently, CMash is being called via relative imports. Since the goal is to migrate to conda, it would be nice if the code just called CMash by looking at the $PATH (or wherever it's been installed). This will head off issues with [planned re-structuring of the CMash repo](https://github.com/dkoslicki/CMash/issues/18).

**Comment by nlapier2** [comment]
The recent update has done this for minimap2, KMC, and CMash.
