### ISSUE TITLE
Training file names contain “.gz.gz”

### ISSUE THREAD

**Issue by dkoslicki** [nlapier2/Metalign#29]
Eg. `taxid_2103_3_genomic.fna.gz.gz` I count 766 such cases in the `/data/organism_files/` directory.

When I retrain (see #25 ), will bad things happened if I replace these by removing the extra `.gz`? Can’t retrain CMash since it can’t detect the file format with double gz’s.

**Comment by nlapier2** [comment]
Hm, odd. Upon investigation, it seems that these are truly "double gzipped" -- running gzip -d on them makes them a regular gzipped file with one .gz extension (such that if you ran gzip -d on _that_ file, you'd get a regular fasta file). We'll have to fix this eventually, but if you want to get started on the retraining as quickly as possible, you can gzip -d all the ".gz.gz" files.

**Comment by dkoslicki** [comment]
Yup, that's what I ended up doing (guess I should have updated this comment when I figured that out)

**Comment by nlapier2** [comment]
The recent update has fixed these files; they should now have a regular (single) '.gz' extension like the rest of the files.
