### ISSUE TITLE
FASTA and FASTQ support

### ISSUE THREAD

**Issue by dkoslicki** [nlapier2/Metalign#3]
It appears KMC is expecting FASTQ formatted input in [these lines](https://github.com/nlapier2/Metalign/blob/master/select_db.py#L56-L58):
```bash
KMC/bin/./kmc -v -k60 -fq -ci2 -cs3 -t48 -jlog_sample test/small_cami_low.fasta test/reads_60mers test/
Error: some error while reading fastq file, please contact authors
```
yet
```bash
KMC/bin/./kmc -v -k60 -fa -ci2 -cs3 -t48 -jlog_sample test/small_cami_low.fasta test/reads_60mers test/
```
runs just fine.

We should either specify in the man page that FASTQ is expected, or else add functionality to handle either FASTA or FASTQ (the better choice).

**Comment by nlapier2** [comment]
Good suggestion. I've added the option for the user to specify either one, with the default being attempted auto-detection based on file name extension.
