### ISSUE TITLE
Using paired read files as input

### ISSUE THREAD

**Issue by vrou1995** [nlapier2/Metalign#31]
Hi,

Is there any way to use paired reads as an input as Kraken2 does?

If not, what read merging software would you recommend?

Thanks!

**Comment by nlapier2** [comment]
Hi,

Thanks for your interest in Metalign! We can process paired end reads properly, but not when they are stored in two separate files (though we hope to add support for that eventually). Personally, I've found BBMap to be a good way to interleave separate paired-end files.

Best,
Nathan
