### ISSUE TITLE
setup_libraries.sh file missing

### ISSUE THREAD

**Issue by arvidgollwitzer** [nlapier2/Metalign#38]
where can the "setup_libraries.sh" file be found?
Is it necessary to work with "setup_libraries.sh" when installing Metalign via bioconda?

**Comment by nlapier2** [comment]
Hi,

Thanks for pointing this out. We removed this setup_libraries script from the repo a while ago but I forgot to update the wiki. To be clear, **Bioconda is the preferred installation method**, and you should not attempt to install the libraries manually (which is essentially what the setup_libraries script was doing) unless you can't (or really don't want to) use Bioconda. The instructions have been updated to reflect this.

Thanks,
Nathan

**Comment by arvidgollwitzer** [comment]
Hi Nathan,

Thank you so much for the quick response!
Best 
Arvid
