### ISSUE TITLE
CMash need not be run with kmer sizes down to 30

### ISSUE THREAD

**Issue by dkoslicki** [nlapier2/Metalign#4]
In [this line](https://github.com/nlapier2/Metalign/blob/master/select_db.py#L81-L82), we do not need CMash to be run with `30-60-10`, as we only use 60-mers in the downstream analysis.

**Comment by nlapier2** [comment]
What should I replace that with? Can I just do "60" or would I have to do something like "60-60-10"? Would I also have to re-do the filter?

**Comment by dkoslicki** [comment]
You would not need to redo the filter. Also, 60-60-10 will work (but note that it will change the dimensions of the resulting tsv file, but this might not matter if you just take the last column in your code currently).

**Comment by nlapier2** [comment]
Changing to 60-60-10 for the StreamingQueryDNADatabase call seems to change the results (even though I only took the last column originally)... does this make any sense?

**Comment by dkoslicki** [comment]
That's odd! It really shouldn't change things, but I would need to look into this further...

**Comment by dkoslicki** [comment]
This issue has now been fixed. See [here](https://github.com/dkoslicki/CMash/issues/19) for more details. Will be implemented in next release of CMash. In short, reverse complements were not being added to the ternary search trie (and a few other insidious bugs).
