### ISSUE TITLE
After conda installation, metalign command does not work

### ISSUE THREAD

**Issue by mahmudhera** [nlapier2/Metalign#43]
(This may be a simple issue that can be immediately closed)

I used the conda installation instruction from [here](https://github.com/nlapier2/Metalign/wiki) on two different machines. After completing the installation, the command `metalign` is not found by the system. (Should I be trying to invoke some other command?)

I could not immediately figure out how to run the tool only from [this](https://github.com/nlapier2/Metalign/wiki) and [this](https://github.com/nlapier2/Metalign/tree/master/example). I have tried to clone the git repository and then run on what I have cloned, but I am not sure what to do next. Should I be downloading data using the shell script? How should I build my own database, and/or how should I use the database?

**Comment by nlapier2** [comment]
Hello, and thanks for your interest in Metalign. The command you should use is "metalign.py", not just "metalign". Can you try and [see if this works](https://github.com/nlapier2/Metalign/wiki/Running-some-example-data)?

First, you'll need to download the database as described [here](https://github.com/nlapier2/Metalign/wiki) (by running setup_data.sh). Currently we do not support building a custom database, and we are unlikely to add this feature in the future, unfortunately.

**Comment by mahmudhera** [comment]
Yeah, the command `metalign.py` works. I thought the conda installation will install a command not named same as the script, hence the confusion. Perhaps an additional line in the readme mentioning the name might be helpful. Thanks!
