### ISSUE TITLE
Indicate to user where the subset database exists

### ISSUE THREAD

**Issue by dkoslicki** [nlapier2/Metalign#8]
I see it's in some randomly generated folder name under `data`, but this should be described (and maybe allow the user to specify where it goes?).

**Comment by nlapier2** [comment]
The metalign.py wrapper script currently abstracts the intermediate steps such as the placement of the subset database away for simplicity. The option is available when running the two steps separately, and is covered in the new docs (see --db option for select_db.py).

Do you think we should add this option to the metalign.py wrapper?

**Comment by dkoslicki** [comment]
I think how you have it now works. I'll close if there are no objections.
